name: Leak prevention

on:
  - push
  - pull_request

jobs:
  gitleaks:
    name: Gitleaks action
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      # —— Github Actions setup —————————————————————————————————————————————

      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # —— Leak prevention ——————————————————————————————————————————————————

      # https://github.com/zricethezav/gitleaks-action (community)
      - name: Leak detection
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .github/security/gitleaks.toml
